use winetricks_install function

diff --git a/install-files/bin/wasta-logos64-setup b/install-files/bin/wasta-logos64-setup
--- a/install-files/bin/wasta-logos64-setup
+++ b/install-files/bin/wasta-logos64-setup
@@ -117,7 +117,6 @@ setupPrefix () {
 
     # Copy in winetricks cache.
     if [[ -d $WINETRICKS_DIR ]] && [[ -d $HOME/.cache/winetricks/ ]]; then
-        # --height=150 --width=450 --window-icon=$DIR/resources/wasta-linux.svg \
         rsync -av $WINETRICKS_DIR/winetricks-cache/ $HOME/.cache/winetricks/ | tee >(zenity \
             $ZENITY_SETTINGS \
             --progress --pulsate --auto-close \
@@ -126,7 +125,6 @@ setupPrefix () {
     fi
 
     # Initialize prefix.
-    # --height=150 --width=450 --window-icon=$DIR/resources/wasta-linux.svg \
     "$WINELOADER" wineboot | zenity $ZENITY_SETTINGS \
         --progress --pulsate --auto-close \
         --title="Setting up Wine Prefix" \
@@ -144,7 +142,7 @@ setupPrefix () {
         errorExit "<b>Setup of Logos Wine Prefix failed!</b>"
     fi
 
-    # Make sure residual wineprocesses clear out.
+    # Make sure residual wine processes clear out.
     wait_for_wineserver
 
     # Make registry changes.
@@ -167,64 +165,7 @@ setupPrefix () {
         "dotnet48" \
     )
     for i in "${installs[@]}"; do
-        echo "Running winetricks $i..."
-
-        # TODO: This "hides" any winetricks output. Maybe not a problem if
-        #   everything goes right?
-        # --height=150 --width=450 --window-icon=$DIR/resources/wasta-linux.svg \
-        "$WINETRICKS_EXE" -q $i | zenity $ZENITY_SETTINGS \
-            --progress --pulsate --auto-close \
-            --title="Installing with winetricks" \
-            --text="winetricks $i... \n\n" &
-
-        # Get zenity process id.
-        PID_ZENITY=$!
-
-        # Get firstly created process id, which is running parallel to zenity.
-        PID_PROCESS=$(pgrep -o -P $$)
-
-        progressCheck $PID_ZENITY $PID_PROCESS
-        if [ "$?" -eq 99 ]; then
-            # Zenity canceled, winetricks install didn't complete.
-            errorExit "<b>$i install in Logos Wine Prefix failed!</b>"
-        fi
-
-        # The following is ferion11's method, for reference:
-        # # Make pipe for zenity input.
-        # pipe_winetricks="$(mktemp)"
-        # rm -rf "$pipe_winetricks"
-        # mkfifo "$pipe_winetricks"
-        #
-        # # zenity GUI feedback
-    	# zenity --progress --title="Installing with winetricks $i" \
-        #     --text="Installing with winetricks $i" --pulsate --auto-close \
-        #     --window-icon=$DIR/resources/wasta-linux.svg \
-        #     --height=150 --width=450 < "$pipe_winetricks" &
-        # # Get zenity process id.
-        # PID_ZENITY="${!}"
-        #
-        # "$WINETRICKS_DIR/winetricks" -q $i | tee "$pipe_winetricks"
-        # EC_WINETRICKS=$?
-        #
-        # wait "$PID_ZENITY"
-        # EC_ZENITY=$?
-        #
-        # rm -rf "$pipe_winetricks"
-        #
-        # # NOTE: sometimes the process finishes before the wait command, giving the error code 127
-    	# if [ "$EC_ZENITY" == "0" ] || [ "$EC_ZENITY" == "127" ] ; then
-    	# 	if [ "$EC_WINETRICKS" != "0" ] ; then
-    	# 		wineserver -k
-    	# 		echo "ERROR on : winetricks $i; EC_WINETRICKS: $EC_WINETRICKS"
-    	# 		gtk_fatal_error "The installation was cancelled because of sub-job failure!\n * winetricks ${*}\n  - WINETRICKS_STATUS: ${WINETRICKS_STATUS}"
-    	# 	fi
-    	# else
-    	# 	wineserver -k
-    	# 	gtk_fatal_error "The installation was cancelled!\n * ZENITY_RETURN: ${ZENITY_RETURN}"
-    	# fi
-
-        # Ensure that wineserver finishes.
-        wait_for_wineserver "${WINEPREFIX}"
+        winetricks_install $i
     done
 
     cleanupPrefix
@@ -232,7 +173,6 @@ setupPrefix () {
 
 errorExit () {
     ### Exit script with passed message.
-    #--height=200 --window-icon=$DIR/resources/wasta-linux.svg \
     zenity $ZENITY_SETTINGS \
         --error --no-wrap \
         --title="wasta-logos64-setup: Error" \
@@ -352,6 +292,66 @@ wine_reg_install() {
 
     wait_for_wineserver
     echo "$WINELOADER regedit.exe ${REG_FILENAME} DONE!"
+}
+
+winetricks_install() {
+    echo "Running winetricks $i..."
+
+    # TODO: This "hides" any winetricks output. Maybe not a problem if
+    #   everything goes right?
+    "$WINETRICKS_EXE" -q $i | zenity $ZENITY_SETTINGS \
+        --progress --pulsate --auto-close \
+        --title="Installing with winetricks" \
+        --text="Running \"winetricks $i\"... \n\n" &
+
+    # Get zenity process id.
+    PID_ZENITY=$!
+
+    # Get firstly created process id, which is running parallel to zenity.
+    PID_PROCESS=$(pgrep -o -P $$)
+
+    progressCheck $PID_ZENITY $PID_PROCESS
+    if [ "$?" -eq 99 ]; then
+        # Zenity canceled, winetricks install didn't complete.
+        errorExit "<b>$i install in Logos Wine Prefix failed!</b>"
+    fi
+
+    # The following is ferion11's method, for reference:
+    # # Make pipe for zenity input.
+    # pipe_winetricks="$(mktemp)"
+    # rm -rf "$pipe_winetricks"
+    # mkfifo "$pipe_winetricks"
+    #
+    # # zenity GUI feedback
+    # zenity --progress --title="Installing with winetricks $i" \
+    #     --text="Installing with winetricks $i" --pulsate --auto-close \
+    #     --window-icon=$DIR/resources/wasta-linux.svg \
+    #     --height=150 --width=450 < "$pipe_winetricks" &
+    # # Get zenity process id.
+    # PID_ZENITY="${!}"
+    #
+    # "$WINETRICKS_DIR/winetricks" -q $i | tee "$pipe_winetricks"
+    # EC_WINETRICKS=$?
+    #
+    # wait "$PID_ZENITY"
+    # EC_ZENITY=$?
+    #
+    # rm -rf "$pipe_winetricks"
+    #
+    # # NOTE: sometimes the process finishes before the wait command, giving the error code 127
+    # if [ "$EC_ZENITY" == "0" ] || [ "$EC_ZENITY" == "127" ] ; then
+    # 	if [ "$EC_WINETRICKS" != "0" ] ; then
+    # 		wineserver -k
+    # 		echo "ERROR on : winetricks $i; EC_WINETRICKS: $EC_WINETRICKS"
+    # 		gtk_fatal_error "The installation was cancelled because of sub-job failure!\n * winetricks ${*}\n  - WINETRICKS_STATUS: ${WINETRICKS_STATUS}"
+    # 	fi
+    # else
+    # 	wineserver -k
+    # 	gtk_fatal_error "The installation was cancelled!\n * ZENITY_RETURN: ${ZENITY_RETURN}"
+    # fi
+
+    # Ensure that wineserver finishes.
+    wait_for_wineserver "${WINEPREFIX}"
 }
 
 
