add in demonstration code for alternate winetricks method

diff --git a/install-files/bin/wasta-logos64-setup b/install-files/bin/wasta-logos64-setup
--- a/install-files/bin/wasta-logos64-setup
+++ b/install-files/bin/wasta-logos64-setup
@@ -120,6 +120,9 @@ setupPrefix () {
     )
     for i in "${installs[@]}"; do
         echo "Running winetricks $i..."
+
+        # TODO: This "hides" any winetricks output. Maybe not a problem if
+        #   everything goes right?
         "$WINETRICKS_DIR/winetricks" -q $i | zenity \
             --height=150 --width=450 --progress --pulsate --auto-close \
             --window-icon=$DIR/resources/wasta-linux.svg \
@@ -127,7 +130,7 @@ setupPrefix () {
             --text="winetricks $i... \n\n" &
 
         # Get zenity process id.
-        PID_ZENITY="${!}"
+        PID_ZENITY=$!
 
         # Get firstly created process id, which is running parallel to zenity.
         PID_PROCESS=$(pgrep -o -P $$)
@@ -137,6 +140,40 @@ setupPrefix () {
             # Zenity canceled, winetricks install didn't complete.
             errorExit "<b>$i install in Logos Wine Prefix failed!</b>"
         fi
+
+        # The following is ferion11's method, for reference:
+        # # Make pipe for zenity input.
+        # pipe_winetricks="$(mktemp)"
+        # rm -rf "$pipe_winetricks"
+        # mkfifo "$pipe_winetricks"
+        #
+        # # zenity GUI feedback
+    	# zenity --progress --title="Installing with winetricks $i" \
+        #     --text="Installing with winetricks $i" --pulsate --auto-close \
+        #     --window-icon=$DIR/resources/wasta-linux.svg \
+        #     --height=150 --width=450 < "$pipe_winetricks" &
+        # # Get zenity process id.
+        # PID_ZENITY="${!}"
+        #
+        # "$WINETRICKS_DIR/winetricks" -q $i | tee "$pipe_winetricks"
+        # EC_WINETRICKS=$?
+        #
+        # wait "$PID_ZENITY"
+        # EC_ZENITY=$?
+        #
+        # rm -rf "$pipe_winetricks"
+        #
+        # # NOTE: sometimes the process finishes before the wait command, giving the error code 127
+    	# if [ "$EC_ZENITY" == "0" ] || [ "$EC_ZENITY" == "127" ] ; then
+    	# 	if [ "$EC_WINETRICKS" != "0" ] ; then
+    	# 		wineserver -k
+    	# 		echo "ERROR on : winetricks $i; EC_WINETRICKS: $EC_WINETRICKS"
+    	# 		gtk_fatal_error "The installation was cancelled because of sub-job failure!\n * winetricks ${*}\n  - WINETRICKS_STATUS: ${WINETRICKS_STATUS}"
+    	# 	fi
+    	# else
+    	# 	wineserver -k
+    	# 	gtk_fatal_error "The installation was cancelled!\n * ZENITY_RETURN: ${ZENITY_RETURN}"
+    	# fi
 
         # Ensure that wineserver finishes.
         wait_for_wineserver "${WINEPREFIX}"
